baseurl                  = "https://example.com"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "SK a ⊸Gᴀʀᴅᴇɴ"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "root"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "digital garden of Sergei Kalabin"

# Metadata for Open Graph and Twitter
    description          = ""               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "SK a ⊸Gᴀʀᴅᴇɴ"
    # rss                = ""

[[params.mainMenu]]
    link = "posts"
    text = "narrative"

[imaging]
    quality = 75
